# Themes from https://github.com/alacritty/alacritty-theme
import = ["~/.config/alacritty/themes/catppuccin-frappe.toml"]

[window]
decorations = "none"
padding = { x = 10, y = 10}
opacity = 0.7
blur = true
startup_mode = "Maximized"

[font]
size = 16.0
normal = { family = "Iosevka Nerd Font", style = "Regular"}
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
